const bookData = [
  {
    title: "《他們都說我遇到了鬼》",
    author: "青色羽翼",
    link: "https://pomelo1122.blog.fc2.com/blog-entry-533.html",
    stars: "★☆☆☆☆",
    meta: "27%棄｜寧天策（小寧） × 沈建國",
    comment: "作者文筆明顯駕馭不了第一人稱，gay受設定也是一大敗筆。",
    plainTags: [],
    watermark: "https://blog-imgs-162.fc2.com/p/o/m/pomelo1122/202505091239366f3.png",
    watermarkWidth: "120px",
    tagA: [],
    tagB: [],
    tagC: [],
    tagD: [],
    tagE: [],
    tagF: [],
    tagG: [],
    tagH: [],
    tagI: [],
    tags: []
  },
  {
    title: "《朕總覺得哪裡不對》",
    author: "青色羽翼",
    link: "https://pomelo1122.blog.fc2.com/blog-entry-532.html",
    stars: "★☆☆☆☆",
    meta: "48%棄｜肖錦意 × 沈君睿",
    comment: "群像寫得很糟糕、笑梗都不好笑、感情線莫名。",
    plainTags: [],
    watermark: "https://blog-imgs-162.fc2.com/p/o/m/pomelo1122/202505091239366f3.png",
    watermarkWidth: "120px",
    tagA: [],
    tagB: [],
    tagC: [],
    tagD: [],
    tagE: [],
    tagF: [],
    tagG: [],
    tagH: [],
    tagI: [],
    tags: []
  },
  // ...後續繼續
];